### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by antfu** [thatoranzhevyy/slidev-theme-zhozhoba#2]
Nice work on the theme!

Would you like to be showcases in our theme gallery?

https://sli.dev/themes/gallery.html

Thanks!

**Comment by thatoranzhevyy** [comment]
> Nice work on the theme!
> 
> Would you like to be showcases in our theme gallery?
> 
> https://sli.dev/themes/gallery.html
> 
> Thanks!

yes, that's why I made this theme and in general I would like to make official themes for slidev.
